name: "Fleet Assistant Connector DEV"
description: "Fleet assistant connector"
version: "2025.11.28"
channel: "dev"
slug: "fleet_assistant_connector_dev"
init: false
url: https://github.com/mjosorg/fleet-assistant-connector-dev
hassio_api: true
#homeassistant_api: true
hassio_role: "backup"
#auth_api: true
privileged:
  - NET_ADMIN
map:
  - config:rw
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  server:
    host: my.VPS.org
    port: 51820
    publickey: inputpublickeyfrommaster
    tunnelip: inputtunnelIP
    enable_backup: false
    installation_id: Installation ID
    fleet_token: Fleet Token
    fleet_assistant_server_ip: Fleet Assistant Server IP

schema:
  server:
    host: str
    port: port
    publickey: str
    tunnelip: str
    enable_backup: bool
    installation_id: str
    fleet_token: str
    fleet_assistant_server_ip: str
